### ISSUE TITLE
add explanation why plants grow well together

### ISSUE THREAD

**Issue by arekkas** [serlo-org/PlantBuddies#2]
It would be awesome if there was an explanation why, for example, apples and strawberries grow well together (or why not)

**Comment by elbotho** [comment]
Thank you 👍 
All the "Hmm, …, what a charmer!" will be general points on what makes this plant special / what pests it can repel etc.
And the "Wow, I mean really this is really long and stuff" is the explanation why those two go together well.

**Comment by arekkas** [comment]
perfect
