### ISSUE TITLE
German Version

### ISSUE THREAD

**Issue by elbotho** [serlo-org/PlantBuddies#7]
- [x] make fields available to translators
- [x] translation (ongoing)
- [x] UX considerations? (can we use js to check browser lang)
- [ ] add impressum

**Comment by szekelygobe** [comment]
Hi there !
If possible I can translate to hungarian and romanian.

**Comment by elbotho** [comment]
@szekelygobe wow, that would by great.
I'll contact you if the technical changes are made.

**Comment by szekelygobe** [comment]
Ok!

**Comment by elbotho** [comment]
@szekelygobe: ok, the german version is in the making now. we will probably try it with two languages first, but if you like you could already start with the Hungarian version.
As a quick solution I put the data onto a google sheet so you can just go ahead and edit it there:

- **Plant Data** https://docs.google.com/spreadsheets/d/1eOdixTLdarMksMluRatbiyLa9lqkzb_U0zbv0A_KF14/edit#gid=1776232699
- **Relations Data** https://docs.google.com/spreadsheets/d/1eOdixTLdarMksMluRatbiyLa9lqkzb_U0zbv0A_KF14/edit#gid=1007116790

**Comment by elbotho** [comment]
while we run this without a backend I will use some easy code to get the browser-language info that is available via js and fall back to **EN** it that fails.

(user can choose own language via menu in any case )
```
var language = navigator.languages && navigator.languages[0] ||
               navigator.language ||
               navigator.userLanguage;

```

**Comment by szekelygobe** [comment]
@elbotho : Ok, I started to translate into Hungarian. For a couple of weeks I have some projects to run, after that I will translate the whole sheet into Hungarian.
